import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Epilogue } from "next/font/google";
import "../globals.css";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const DynamicSidebar = dynamic(() => import("@/components/layout/Sidebar"));
  const DynamicMainbar = dynamic(() => import("@/components/layout/Mainbar"));
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <main>
          <div className="bg-background">
            <div className="flex flex-row">
              <div className="hidden lg:block w-[20%] border-r">
                <DynamicSidebar />
              </div>
              <div className="col-span-3 overflow-auto lg:col-span-5 w-[80%]">
                <DynamicMainbar />
                {children}
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
